name 'ibm_mq'
maintainer 'IBM'
maintainer_email 'arthur.barr@uk.ibm.com'
license 'Apache 2.0'
description 'Installs/Configures IBM MQ'
long_description 'Installs/Configures IBM MQ'
version '0.1.1'
depends 'limits'
depends 'yum'
supports 'ubuntu'
